apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: scp9oikad-go 
  janus-idp.io/tekton: scp9oikad-go
  backstage.io/kubernetes-id: scp9oikad-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: scp9oikad-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml